theme: jekyll-theme-minimal
title: Chenguang's homepage
description: 

social_links: 
  email: cgduan.math@whu.edu.cn, cg.duan@outlook.com

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
  - LICENSE

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-scholar
