theme: jekyll-theme-minimal
title: Chenguang's homepage
description: 

social_links: 
  github: https://github.com/chenguangduan
  email: cgduan.math@whu.edu.cn, cg.duan@outlook.com

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
  - LICENSE

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-scholar

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Your Name"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "publications"
    values:
      layout: "publication"

collections:
  publications:
    output: true
    permalink: /publications/:path/

scholar:
  style: apa
  locale: en
  sort_by: year,month
  order: descending
  source: ./_bibliography
  bibliography: papers.bib
  bibliography_template: publication
  replace_strings: true
  join_strings: true
  details_dir: bibliography
  details_layout: bibtex.html
  details_link: 
  query: "@*"
  group_by: year
  group_order: descending

  
    
